apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-tunnel
  labels:
    app: ssh-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-tunnel
  template:
    metadata:
      labels:
        app: ssh-tunnel
    spec:
      containers:
        - name: ssh-tunnel
          image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/ssh-tunnel:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 22
            - containerPort: 8080
          env:
            - name: BROKER_USER
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: user
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: password

---

kind: Service
apiVersion: v1
metadata:
  name: ssh-tunnel
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      name: ssh
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ssh-tunnel

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-tunnel-config
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
  authorized_keys: |
    ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABAQDHP0lVoS7GxcidaAP5x84JucEti9/G+Bq54ECXfuVwoEgxGr9LN2SsDL4xFDEWkp4/5ty4PkDF5ZyXHd7w7uOEhVEcvCbsAM18nX2+6soEzU+WfET22DlpnxjvXiCRL79ogQmC3m6GYoDfCHy4u9elVbQRM66ZfAk9XH/POAFXDApjErsCYPDqNpeGNK7wJr9IAIP0dpfbPD2HVlU8fAnw364uAJ/+76U41/4Yy7THqQg6+9YFx4bfd3oSS19dV6uvzZfYjMvBQVsvojFYmFgqMhdke2s8JHUVIaABVWg6AZPCTXSnajQyUzPGDFeoyUJ9mQwfUGqDcc2vcm7OufbX rsa-key-20220404
