apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-tunnel
  labels:
    app: ssh-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-tunnel
  template:
    metadata:
      labels:
        app: ssh-tunnel
    spec:
      containers:
        - name: ssh-tunnel
          image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/ssh-tunnel:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 22
            - containerPort: 8080
          env:
            - name: BROKER_USER
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: user
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: password
          volumeMounts:
            - name: ssh-volume
              mountPath: /home/jboss/.ssh/authorized_keys
        volumes:
          - name: ssh-volume

---

kind: Service
apiVersion: v1
metadata:
  name: ssh-tunnel
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      name: ssh
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ssh-tunnel